// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnpKgAX6G9wq3otJa6nPNOYSVhRyd2q8Y',
    appId: '1:373024204595:web:7de997c3b1702fecde4046',
    messagingSenderId: '373024204595',
    projectId: 'final-year-project-v2-46a8a',
    authDomain: 'final-year-project-v2-46a8a.firebaseapp.com',
    storageBucket: 'final-year-project-v2-46a8a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhD-FDpxXVf88YuI_keURNi-hVD9hPONs',
    appId: '1:373024204595:android:04953f21a3a561d8de4046',
    messagingSenderId: '373024204595',
    projectId: 'final-year-project-v2-46a8a',
    storageBucket: 'final-year-project-v2-46a8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvhk9GbBnpWEHH82_-e30SfZPyA0Wo-Tc',
    appId: '1:373024204595:ios:a62f6a60226b5195de4046',
    messagingSenderId: '373024204595',
    projectId: 'final-year-project-v2-46a8a',
    storageBucket: 'final-year-project-v2-46a8a.firebasestorage.app',
    iosBundleId: 'com.example.shopper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvhk9GbBnpWEHH82_-e30SfZPyA0Wo-Tc',
    appId: '1:373024204595:ios:a62f6a60226b5195de4046',
    messagingSenderId: '373024204595',
    projectId: 'final-year-project-v2-46a8a',
    storageBucket: 'final-year-project-v2-46a8a.firebasestorage.app',
    iosBundleId: 'com.example.shopper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnpKgAX6G9wq3otJa6nPNOYSVhRyd2q8Y',
    appId: '1:373024204595:web:45882f43e7860609de4046',
    messagingSenderId: '373024204595',
    projectId: 'final-year-project-v2-46a8a',
    authDomain: 'final-year-project-v2-46a8a.firebaseapp.com',
    storageBucket: 'final-year-project-v2-46a8a.firebasestorage.app',
  );
}
